model_list:
  # Модели OpenAI
  - model_name: "openai/*"
    litellm_params:
      model: "${model_name}"
      openai_api_key: "${OPENAI_API_KEY}"
      proxy:
        http: "${HTTP_PROXY}"
        https: "${HTTPS_PROXY}"
        no_proxy: "${NO_PROXY}"
      model_identifier: "${model_name}-id"
      model_details:
        description: "OpenAI model ${model_name}"

  # Модели Hugging Face
  - model_name: "huggingface/*"
    litellm_params:
      model: "${model_name}"
      huggingface_api_key: "${HUGGINGFACE_API_KEY}"
      proxy:
        http: "${HTTP_PROXY}"
        https: "${HTTPS_PROXY}"
        no_proxy: "${NO_PROXY}"
      model_identifier: "${model_name}-id"
      model_details:
        description: "Hugging Face model ${model_name}"

  # Модели Anthropic
  - model_name: "anthropic/*"
    litellm_params:
      model: "${model_name}"
      anthropic_api_key: "${ANTHROPIC_API_KEY}"
      proxy:
        http: "${HTTP_PROXY}"
        https: "${HTTPS_PROXY}"
        no_proxy: "${NO_PROXY}"
      model_identifier: "${model_name}-id"
      model_details:
        description: "Anthropic model ${model_name}"

  # Модели Cohere
  - model_name: "cohere/*"
    litellm_params:
      model: "${model_name}"
      cohere_api_key: "${COHERE_API_KEY}"
      proxy:
        http: "${HTTP_PROXY}"
        https: "${HTTPS_PROXY}"
        no_proxy: "${NO_PROXY}"
      model_identifier: "${model_name}-id"
      model_details:
        description: "Cohere model ${model_name}"

  # Модели Together
  - model_name: "together/*"
    litellm_params:
      model: "${model_name}"
      together_api_key: "${TOGETHER_API_KEY}"
      proxy:
        http: "${HTTP_PROXY}"
        https: "${HTTPS_PROXY}"
        no_proxy: "${NO_PROXY}"
      model_identifier: "${model_name}-id"
      model_details:
        description: "Together model ${model_name}"

  # Модели ngrok (если применимо)
  - model_name: "ngrok/*"
    litellm_params:
      model: "${model_name}"
      ngrok_api_key: "${NGROK_API_KEY}"
      proxy:
        http: "${HTTP_PROXY}"
        https: "${HTTPS_PROXY}"
        no_proxy: "${NO_PROXY}"
      model_identifier: "${model_name}-id"
      model_details:
        description: "ngrok model ${model_name}"

  # Модели Anyscale
  - model_name: "anyscale/*"
    litellm_params:
      model: "${model_name}"
      anyscale_api_key: "${ANYSCALE_API_KEY}"
      proxy:
        http: "${HTTP_PROXY}"
        https: "${HTTPS_PROXY}"
        no_proxy: "${NO_PROXY}"
      model_identifier: "${model_name}-id"
      model_details:
        description: "Anyscale model ${model_name}"

  # Модели Ollama
  - model_name: "ollama/*"
    litellm_params:
      model: "${model_name}"
      ollama_api_base: "${OLLAMA_API_BASE}"
      proxy:
        http: "${HTTP_PROXY}"
        https: "${HTTPS_PROXY}"
        no_proxy: "${NO_PROXY}"
      model_identifier: "${model_name}-id"
      model_details:
        description: "Ollama model ${model_name}"

litellm_settings:
  callbacks: ["prometheus"]
