global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ollama'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ollama:9000']

  - job_name: 'open-webui'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['open-webui:8001']

  - job_name: 'r2r'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['r2r:7272']

  - job_name: 'postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres:9187']

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8082']

  # - job_name: 'pipelines'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['pipelines:9099']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
